### ISSUE TITLE
Failing to upload: Error! Unexpected server error.

### ISSUE THREAD

**Issue by garrows** [zeit/now-client#29] opened 2016-09-07 06:17 UTC
Getting an error back from `now`.
```
> Deploying ~/os/lgtm
> Using Node.js 6.2.1 (default)
> Ready! https://lgtm-wcrikbxjtv.now.sh (copied to clipboard) [2s]
> Error! Upload failed
> Error! Unexpected server error. Please retry.
```
retrying with the same commit sits on `Initializing...` at 0% forever. 
Making a new commit and retrying gives me  `Error! Unexpected server error. Please retry.` again.

Others reporting the same in the slack channel https://zeit-community.slack.com/archives/now/p1473213456000629

**Comment by rase-** [comment] 2016-09-07 08:12
Sorry about that. File syncing was broken for a little bit due to a regression a couple hours ago. :( Fixed now!

**Closed by rase-** 2016-09-07 08:12 UTC

**Comment by garrows** [comment] 2016-09-07 10:32
I had to use `now -f -d` in the end but it works now. Thanks.
